## Working with Text Files

- Reading from a text file

In [1]:
file = open("./data/story.txt", "r")

text = file.read()
print(text)

file.close()

A clever monkey named Momo lived by a river and used a large, flat stone to hop over to an island for delicious fruit.
A sneaky crocodile decided to wait on that stone to catch him. Recognizing the "stone" was actually the crocodile,
Momo tricked it into opening its mouth, then quickly hopped on its head to safely cross the river.

- Text formatting

In [2]:
# removing unwanted characters from the text
unwanted_char = [',', '.', ';', ':', '!', '?', '\'', '\"', '\t', '\n', '  ']
for char in unwanted_char:
    text = text.replace(char, ' ')
text = text.strip()
print(f"Clean text = {text}|")

# converting text to lowercase
text = text.lower()
print(f"lowered = {text}")

# finding frequencies for each letter
letter_frequency = {}
for letter in text:
    letter_frequency[letter] = text.count(letter)
print(f"Letter frequencies = {letter_frequency}")

# splitting text into words
words = text.split(' ')
print(f"Words = {words}")

# finding unique words
unique = set(words)
print(f"Unique words = {unique}")

# finding word count
print(f"Total word count = {len(words)}")
print(f"Unique word count = {len(unique)}")

# finding frequencies for each word
word_frequency = {}
for word in unique:
    word_frequency[word] = words.count(word)
print(f"Word frequencies = {word_frequency}")

Clean text = A clever monkey named Momo lived by a river and used a large flat stone to hop over to an island for delicious fruit A sneaky crocodile decided to wait on that stone to catch him Recognizing the stone was actually the crocodile Momo tricked it into opening its mouth then quickly hopped on its head to safely cross the river|
lowered = a clever monkey named momo lived by a river and used a large flat stone to hop over to an island for delicious fruit a sneaky crocodile decided to wait on that stone to catch him recognizing the stone was actually the crocodile momo tricked it into opening its mouth then quickly hopped on its head to safely cross the river
Letter frequencies = {'a': 19, ' ': 60, 'c': 14, 'l': 12, 'e': 29, 'v': 5, 'r': 14, 'm': 8, 'o': 29, 'n': 17, 'k': 4, 'y': 6, 'd': 14, 'i': 21, 'b': 1, 'u': 6, 's': 13, 'g': 4, 'f': 4, 't': 25, 'h': 11, 'p': 4, 'w': 2, 'z': 1, 'q': 1}
Words = ['a', 'clever', 'monkey', 'named', 'momo', 'lived', 'by', 'a', 'river', 'and', 'used', 'a', 'large', 'flat', 'stone', 'to', 'hop', 'over', 'to', 'an', 'island', 'for', 'delicious', 'fruit', 'a', 'sneaky', 'crocodile', 'decided', 'to', 'wait', 'on', 'that', 'stone', 'to', 'catch', 'him', 'recognizing', 'the', 'stone', 'was', 'actually', 'the', 'crocodile', 'momo', 'tricked', 'it', 'into', 'opening', 'its', 'mouth', 'then', 'quickly', 'hopped', 'on', 'its', 'head', 'to', 'safely', 'cross', 'the', 'river']
Unique words = {'fruit', 'sneaky', 'was', 'named', 'its', 'cross', 'to', 'for', 'an', 'that', 'island', 'used', 'crocodile', 'it', 'head', 'lived', 'catch', 'river', 'large', 'momo', 'over', 'clever', 'hop', 'him', 'safely', 'delicious', 'decided', 'actually', 'mouth', 'monkey', 'flat', 'opening', 'on', 'and', 'then', 'recognizing', 'hopped', 'by', 'a', 'quickly', 'stone', 'wait', 'into', 'the', 'tricked'}
Total word count = 61
Unique word count = 45
Word frequencies = {'fruit': 1, 'sneaky': 1, 'was': 1, 'named': 1, 'its': 2, 'cross': 1, 'to': 5, 'for': 1, 'an': 1, 'that': 1, 'island': 1, 'used': 1, 'crocodile': 2, 'it': 1, 'head': 1, 'lived': 1, 'catch': 1, 'river': 2, 'large': 1, 'momo': 2, 'over': 1, 'clever': 1, 'hop': 1, 'him': 1, 'safely': 1, 'delicious': 1, 'decided': 1, 'actually': 1, 'mouth': 1, 'monkey': 1, 'flat': 1, 'opening': 1, 'on': 2, 'and': 1, 'then': 1, 'recognizing': 1, 'hopped': 1, 'by': 1, 'a': 4, 'quickly': 1, 'stone': 3, 'wait': 1, 'into': 1, 'the': 3, 'tricked': 1}

- Writing into a text file

In [3]:
file = open("./data/output.txt", "w")

file.write("Word         : Frequency\n")
for word in word_frequency:
    file.write(f"{word:12} : {word_frequency[word]}\n")

file.close()

In [4]:
file = open("./data/output.txt", "w")

file.write("Letter : Frequency\n")
for letter in letter_frequency:
    file.write(f"{letter} : {letter_frequency[letter]}\n")

file.close()

## Loading a CSV/JSON File into a Pandas DataFrame

In [5]:
import pandas as pd

table = pd.read_csv("./data/dataset.csv")
table.head()

   sepal length  sepal width  petal length  petal width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
import pandas as pd

table = pd.read_json("./data/dataset.json")
table.head()

   sepal length  sepal width  petal length  petal width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Working with Pandas DataFrames

In [3]:
import pandas as pd

table = pd.read_csv("./data/dataset.csv")
table.head()

   sepal length  sepal width  petal length  petal width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

To access particular rows, columns or cells - we use the following syntax:

```
    # Syntax:
    table.loc[row_filter, col_filter]
```

If you don't want to apply a filter, put `:` instead

- accessing specific a row (using row index)

In [4]:
my_row = table.loc[0, :]

print(my_row)

sepal length       5.1
sepal width        3.5
petal length       1.4
petal width        0.2
species         setosa
Name: 0, dtype: object

- accessing specific a column (using column name)

In [5]:
my_col = table.loc[:, 'sepal length']

print(my_col)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length, Length: 150, dtype: float64

- accessing specific cells

In [6]:
my_cell = table.loc[2, 'sepal length']

print(my_cell)

4.7

- filtering rows based on condition

In [10]:
filtered = table[table['sepal length'] > 7]

print(filtered)

     sepal length  sepal width  petal length  petal width    species
102           7.1          3.0           5.9          2.1  virginica
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
125           7.2          3.2           6.0          1.8  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

- sorting rows based on columns

In [12]:
sorted = table.sort_values(by='sepal length', ascending=True)

print(sorted)

     sepal length  sepal width  petal length  petal width    species
13            4.3          3.0           1.1          0.1     setosa
8             4.4          2.9           1.4          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [13]:
sorted = table.sort_values(by=['sepal length', 'sepal width'], ascending=[True, False])

print(sorted)

     sepal length  sepal width  petal length  petal width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]